ubuntu_mirror: "http://jp.archive.ubuntu.com/ubuntu/"
system_locale: "ja_JP.UTF-8"
timezone: "Asia/Tokyo"
jupyterlab_user: "sakaztk"
jupyterlab_group: "sakaztk"
jupyterlab_use_redirect_file: False
jupyterlab_browser: "/mnt/c/Program\\ Files\\ \\(x86\\)/Microsoft/Edge/Application/msedge.exe %s"

ansible_env_user: "sakaztk"
ansible_packages:
  - python3
  - python3-venv
  - python3-pip
  - git
  - podman
  - graphviz
ansible_pip_packages:
  - ansible
  - ansible-core
  - ansible-lint
  - ansible-runner
  - ansible-navigator
  - ansible-autodoc
  - molecule
  - molecule-plugins
  - pytest
  - testinfra
  - pytest-testinfra
  - sops
  - yamllint
