dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu2404
#    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    image: docker.io/ubuntu/24.04
    pre_build_image: true
    privileged: true
    user: root

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    vvv: true
  env:
    ANSIBLE_ROLES_PATH: ../../../../roles/

scenario:
  name: default
verifier:
  name: ansible